### ISSUE TITLE
tail: cannot open '/var/log/backup.log' for reading: No such file or directory

### ISSUE THREAD

**Issue by ishtiyaq** [williarin/secure-mysql-backups#6]
## Problem
Line number `13` in the `src/run-cron` file is adding the log to the `/var/log/backup.log` file but this file does not exist for the first time 
run.

```bash
echo "$cron_time backup >> /var/log/backup.log" > /etc/crontabs/root
```

### Error
```bash
tail: cannot open '/var/log/backup.log' for reading: No such file or directory
````

## Solution
Please add below lines before line number 13 in `src/run-cron` file

```bash
if [ ! -f "/var/log/backup.log" ]; then
    touch /var/log/backup.log
fi
```

**Comment by williarin** [comment]
Thanks @ishtiyaq, I fixed it in https://github.com/williarin/secure-mysql-backups/releases/tag/1.1.1.
